### ISSUE TITLE
Upload LucidChart diagrams.

### ISSUE THREAD

**Issue by L1ghtman2k** [ScoreTrak/ScoreTrak#1]
This is a request (for my self) to upload lucidchart diagrams for documentation purposes

**Comment by thisisibrahimd** [comment]
Create SQL Diagram with drawsql.app.
https://drawsql.app/scoretrak/diagrams/scoretrak.
Will add to doc repo.

**Comment by L1ghtman2k** [comment]
`drawsql.app` is amazing, very nice diagram! I actually had the lucidchart diagram, but it was hard to update, and it wasn't nearly as easy to share or interact with. Very well done

**Comment by L1ghtman2k** [comment]
Also, feel free to close this issue whenever you see fit, as far as the content of the diagram, it looks correct

**Comment by thisisibrahimd** [comment]
Thanks! If there is any error, just let me know and I can update it. We could also apply for open source account so we can have two people the in the scoretrak team in the drawsql app.

https://github.com/ScoreTrak/ScoreTrak.github.io/pull/2/commits/8fa62f6223e8e5cf317a7e7982fc05de23aa44d7
