### ISSUE TITLE
Create Helm chart for easier k8s deployment

### ISSUE THREAD

**Issue by L1ghtman2k** [ScoreTrak/ScoreTrak#145]

**Comment by thisisibrahimd** [comment]
Can I help you out on this? I have some experience with Helm chart and k8s deployment.

**Comment by L1ghtman2k** [comment]
> Can I help you out on this? I have some experience with Helm chart and k8s deployment.

I would appreciate that! Let me know If I could be of any help, or if I could clarify anything!

**Comment by thisisibrahimd** [comment]
Looking more into the repo, I believe there are more steps that need to be taken before a proper/scalable helm/k8s deployment can be made.

Here are my suggestion, let me know what you think
- Separate Server and Client repo into different repos as commits can be tagged and docker images can be built and deploy to GitHub container registry as there is no container registry as of yet. Example:
	- ScoreTrak-Server repo, All go files related to the server.
	- ScoreTrak-Client repo, All the react files in the web folder.
- Creating a helm-charts repo in the ScoreTrak Org as I can't and that would be the best place to store future charts. Here are some examples of helm-charts repos.
	- https://github.com/elastic/helm-charts
	- https://github.com/grafana/helm-charts
	- https://github.com/cockroachdb/helm-charts

**Comment by L1ghtman2k** [comment]
This sounds good, I have just created the https://github.com/ScoreTrak/helm-charts repo,

At the moment, with every merge to the main branch, GitHub actions push the client and server docker images to: https://hub.docker.com/u/l1ghtman, but there is no tagging/versioning, which isn't ideal at all. Let me do a quick research on how I could set this up for this Github.

As to splitting ScoreTrak-Server, and ScoreTrak-Client, I have kind of debated on this for a while. Originally, that is how it was until I decided to merge them into one, because I was following this project layout: https://github.com/golang-standards/project-layout/tree/master/web. Though, it seems like your approach makes more sense, given that we can tag/version/package directly in GitHub

**Comment by thisisibrahimd** [comment]
Thanks for creating the repo. Going to structure for later use.

Ohh awesome. tagging is ideal but it won't be the end of the world. 

That project layout is very nice. However, I believe it assume that your go server will be serving the website but in this case, it is not. Therefore, it seems weird to have one github repo produce two docker images. It is possible to make it work but it won't be pretty. I believe this would also complicate putting an envoy proxy between them, I might be wrong on this one tho.

**Comment by L1ghtman2k** [comment]
I fully agree that a single repo shouldn't be creating two docker images, and now that you mentioned, the go backend does not serve the website, so splitting them make sense. 

For now, I have created the ScoreTrak-Client repo, where I will migrate everything from the web/ folder, and in addition, I will set up GitHub actions to push directly to github packages, instead of my personal registry.
(I will keep the ScoreTrak/ScoreTrak repo for the backend for now, and will rename it to ScoreTrak-Server once we migrate out all of the components.)

If we go this way, it might also make sense to create a separate ScoreTrak/Deployment repo, where we can organize things from Deployment/ folder, what are your thoughts?

**Comment by thisisibrahimd** [comment]
Splitting make sense. Looking forward to seeing both container registry help. I can help with that as well, if needed. I will keep lookout for when the ScoreTrak/Client repo is migrated if not done already.

That repo makes sense. I was thinking more ScoreTrak/Docs and store all the knowledge there. We could even add the ScoreTrak/Docs repo into the others as a submodules so users can know that it exists.

Thanks for the invite 👍 .

**Comment by L1ghtman2k** [comment]
I just did the following
- Renamed ScoreTrak-Client to client
- migrated web/ to ScoreTrak/client
- removed web/ from ScoreTrak/ScoreTrak
- Setup github actions to create docker images, and push them into github registry on new release for both client and server

For some reason, GitHub yields a wired behavior when creating packages:
For client:
![image](https://user-images.githubusercontent.com/35672535/120116699-6245f700-c157-11eb-8d62-2aa9c4f7b89f.png)
For server:
![image](https://user-images.githubusercontent.com/35672535/120116762-ad600a00-c157-11eb-924a-c6a94d9e0cb9.png)

Even though, both have packages created, the client doesn't display it correctly
