### ISSUE TITLE
Create grpc health probes for k8s deployments 

### ISSUE THREAD

**Issue by thisisibrahimd** [ScoreTrak/ScoreTrak#237]
Add grpc health probe to the server so k8s can check how it is doing.

https://github.com/grpc-ecosystem/grpc-health-probe

**Comment by L1ghtman2k** [comment]
Example app: https://github.com/americanexpress/grpc-k8s-health-check

**Comment by thisisibrahimd** [comment]
https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by thisisibrahimd** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe

**Comment by thisisibrahimd** [comment]
Now that grpc is officially  supporting grpc health probe and k8s can launch probe to the master server, I think the pr in the scoretrak apis is the best way to go about this.
