### ISSUE TITLE
Improve Docker Image Size

### ISSUE THREAD

**Issue by thisisibrahimd** [ScoreTrak/ScoreTrak#252]
Decrease the size of the docker images from 1.9 GB to 60mb.

Used this resource to implement it. https://contains.dev/blog/optimizing-docker-image-size

**Comment by thisisibrahimd** [comment]
Since we intended to utilized sqlite in the future, we can safely switch to the golang:1.17-alpine base container.

**Comment by thisisibrahimd** [comment]
![Screen Shot 2022-02-24 at 22 11 24](https://user-images.githubusercontent.com/20114089/155646628-968255ba-16e8-41cc-92e2-a3f5dea20c1f.png)

Note: majority of the size comes from the go mod download.
We could potentially use golang as a builder and use golang:alpine by simply copying the generated binary into it.

**Comment by L1ghtman2k** [comment]
yeah, I think we can definitely get multistage docker builds to handle this for us.
Don't think we need to really think about sqlite support until we get there, just good to keep in mind

**Comment by thisisibrahimd** [comment]
> yeah, I think we can definitely get multistage docker builds to handle this for us. Don't think we need to really think about sqlite support until we get there, just good to keep in mind

We don't however, when we build with CGO_enabled=0, we had trouble running in k8s for some reason.
