### ISSUE TITLE
Cannot Upload Old Competition. 

### ISSUE THREAD

**Issue by Vasu-Baldwa** [ScoreTrak/ScoreTrak#296]
When uploading an exported competition, the following error is received:
![image](https://user-images.githubusercontent.com/35380065/166588299-fd25dc22-a3e3-440b-9a7b-ad7ead84d3a8.png)

**Comment by L1ghtman2k** [comment]
This is likely caused because old/identical entities with the same keys already exist in the database. Deleting old objects from either the database, or the .json config could help
