### ISSUE TITLE
Implement Code coverage analysis utility

### ISSUE THREAD

**Issue by L1ghtman2k** [ScoreTrak/ScoreTrak#3]
The following may help:
https://github.com/marketplace/codecov/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNg==#pricing-and-setup

**Comment by thisisibrahimd** [comment]
https://github.com/ScoreTrak/ScoreTrak/commit/1e4aa168deb954f588da6a59672c8d89f5719111#commitcomment-79206818

**Comment by thisisibrahimd** [comment]
https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
